image: maven:3.6.1-jdk-11

stages:
  - build

build and test:
  stage: build
  except:
    - master
  services:
    - docker:dind
  cache:
    paths:
      - .m2/repository/
  script:
    - mvn clean install -s build/settings.xml

build, test and deploy:
  stage: build
  only:
    - master
  services:
    - docker:dind
  cache:
    paths:
      - .m2/repository/
  script:
    - mvn release:prepare -s build/settings.xml
    - mvn release:perform -s build/settings.xml
